# Generated by Django 5.0.1 on 2024-02-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='title',
        ),
    ]
