# Generated by Django 5.0.1 on 2024-02-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docs', '0002_rename_text_subcategory_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='body',
            field=models.CharField(blank=True, null=True),
        ),
    ]
