# Generated by Django 4.2.8 on 2024-02-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('UZ', "O'zbek"), ('RU', 'Русский'), ('EN', 'English')], default='UZ', max_length=2),
        ),
    ]
