# Generated by Django 5.0.1 on 2024-02-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_user_theme_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Unavailable', max_length=30),
        ),
    ]
