# Generated by Django 5.0.1 on 2024-03-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
