# Generated by Django 5.0.1 on 2024-03-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_exceptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exceptions',
            new_name='Exception',
        ),
    ]
