# Generated by Django 4.2.8 on 2024-02-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
