# Generated by Django 5.0.1 on 2024-02-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_alter_ticket_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
